# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [3]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
data = df_food.shape
print(data)

(125, 61)

What are the columns and their types in this data set?

In [5]:
# Show the column names and their types.
columns = df_food.info()
columns

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [6]:
# Remove ‘em.
df_food = df_food[['calories_day', 'weight', 'Gender']]
df_food.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [7]:
# Count ‘em.
df_food.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [8]:
# Drop ‘em.
df_food = df_food.dropna()
df_food.head()

   calories_day                    weight  Gender
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1
5           3.0                       190       1

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [9]:
# Fix that.
df_food['weight'] = pd.to_numeric(
    df_food['weight'],
    errors = 'coerce',
    downcast='float')
df_food = df_food.dropna()
df_food.head()

   calories_day  weight  Gender
1           3.0   155.0       1
4           2.0   190.0       1
5           3.0   190.0       1
6           3.0   180.0       2
7           3.0   137.0       1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [10]:
# Savey save!
df_food.to_csv('../data/food_data_cleaned.csv', index=False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [11]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).

salary_data_set_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'
df_salary = pd.read_csv(salary_data_set_path, index_col=None, sep='\t')
df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [12]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [13]:
# Show the column names and their types.
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [14]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed,	gender, race
df_salary = df_salary.rename(columns={
    'Timestamp': 'timestamp',
    'How old are you?': 'age',
    'What industry do you work in?': 'industry',
    'Job title': 'title',
    'If your job title needs additional context, please clarify here:': 'title_context',
    "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'salary',
    "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.": 'additional_compensation',
    'Please indicate the currency': 'currency',
    'If "Other," please indicate the currency here: ': 'other_currency',
    'If your income needs additional context, please provide it here:': 'salary_context',
    'What country do you work in?': 'country',
    "If you're in the U.S., what state do you work in?" : 'state',
    'What city do you work in?' : 'city',
    'How many years of professional work experience do you have overall?' : 'total_yoe',
    'How many years of professional work experience do you have in your field?' : 'field_yoe',
    'What is your highest level of education completed?' : 'highest_education_completed',
    'What is your gender?': 'gender',
    'What is your race? (Choose all that apply.)' : 'race'
    })
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    28062 non-null  str
 1   age                          28062 non-null  str
 2   industry                     27988 non-null  str
 3   title                        28061 non-null  str
 4   title_context                7262 non-null   str
 5   salary                       28062 non-null  str
 6   additional_compensation      20766 non-null  float64
 7   currency                     28062 non-null  str
 8   other_currency               206 non-null    str
 9   salary_context               3042 non-null   str
 10  country                      28062 non-null  str
 11  state                        23039 non-null  str
 12  city                         27980 non-null  str
 13  total_yoe                    28062 non-null  str
 14  field_yoe                    28062 non-null  str
 15  highest_education_completed  27840 non-null  str
 16  gender                       27891 non-null  str
 17  race                         27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [15]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [16]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)

df_tech_jobs = df_salary[df_salary['industry'] == 'Computing or Tech']

df_tech_jobs.to_csv('../data/df_salary_tech.csv', index=False)

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [17]:
# Sanity Check 
df_salary_tech = pd.read_csv('../data/df_salary_tech.csv')

df_salary_tech.head(10)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
1,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
2,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
3,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
4,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
5,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
6,4/27/2021 11:04:19,35-44,Computing or Tech,Managed Services Sales Coordinator,Primarily proposal writing,"72,000",3000.0,USD,NaN,NaN,United States,Michigan,Troy,11 - 20 years,5-7 years,Master's degree,Woman,White
7,4/27/2021 11:04:36,25-34,Computing or Tech,Technical specialist,NaN,"34,000",2000.0,USD,NaN,NaN,United States,Minnesota,Minneapolis,5-7 years,5-7 years,College degree,Woman,White
8,4/27/2021 11:04:41,35-44,Computing or Tech,Tech Writer,NaN,"88,000",NaN,USD,NaN,NaN,USA,Maryland,prefer not to answer,11 - 20 years,8 - 10 years,College degree,Woman,Another option not listed here or prefer not t...
9,4/27/2021 11:04:49,35-44,Computing or Tech,Senior Business Analyst,NaN,"125,000",NaN,USD,NaN,NaN,US,New York,New York,11 - 20 years,8 - 10 years,Master's degree,Woman,White

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [18]:
# Filtery filter for just the jobs that pay in USD!
df_salary_usd = df_salary_tech[df_salary_tech['currency'] == 'USD']

df_salary_usd.head(10)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
2,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
3,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
4,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
5,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
6,4/27/2021 11:04:19,35-44,Computing or Tech,Managed Services Sales Coordinator,Primarily proposal writing,"72,000",3000.0,USD,NaN,NaN,United States,Michigan,Troy,11 - 20 years,5-7 years,Master's degree,Woman,White
7,4/27/2021 11:04:36,25-34,Computing or Tech,Technical specialist,NaN,"34,000",2000.0,USD,NaN,NaN,United States,Minnesota,Minneapolis,5-7 years,5-7 years,College degree,Woman,White
8,4/27/2021 11:04:41,35-44,Computing or Tech,Tech Writer,NaN,"88,000",NaN,USD,NaN,NaN,USA,Maryland,prefer not to answer,11 - 20 years,8 - 10 years,College degree,Woman,Another option not listed here or prefer not t...
9,4/27/2021 11:04:49,35-44,Computing or Tech,Senior Business Analyst,NaN,"125,000",NaN,USD,NaN,NaN,US,New York,New York,11 - 20 years,8 - 10 years,Master's degree,Woman,White
11,4/27/2021 11:05:08,45-54,Computing or Tech,senior web application developer,NaN,"98,166",0.0,USD,NaN,NaN,United States,Indiana,Indianapolis,21 - 30 years,21 - 30 years,College degree,Man,White

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [19]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_usd['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [20]:
# Replace them all with 'US'.

df_salary_usd['country'] = df_salary_usd['country'].replace({
    'United States of America': 'US', 
    'United States': 'US', 
    'usa':'US',
    'USA': 'US', 
    'U.S.': 'US'
})

Have a look at the count of each unique country again now.

In [21]:
# Count again.
df_salary_usd['country'].value_counts()

country
US                3436
United States       68
Usa                 59
USA                 56
United states       23
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 71, dtype: int64

Did you notice anything interesting?

In [22]:
# Try to clean up all the united states variants (accidentally erased question)
df_salary_clean = (
    df_salary_usd['country']
    .str.lower()
    .str.strip()
    .str.replace('.', '', regex=False)
)

df_salary_clean = df_salary_clean.replace({
    'united states': 'US',
    'united states of america': 'US',
    'usa': 'US',
    'us': 'US'
})

df_salary_usd['country'] = df_salary_clean

In [23]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_usd['country'].value_counts()

country
US                         3710
canada                        5
israel                        5
united state of america       2
unite states                  2
australia                     2
unitedstates                  2
india                         2
singapore                     2
spain                         2
brazil                        2
united kingdom                2
new zealand                   2
poland                        2
france                        2
denmark                       2
nigeria                       2
uniyed states                 1
america                       1
puerto rico                   1
united state                  1
cuba                          1
danmark                       1
italy                         1
international                 1
united stated                 1
remote (philippines)          1
uruguay                       1
mexico                        1
united stateds                1
isa                           1
pakistan                      1
netherlands                   1
china                         1
san francisco                 1
romania                       1
japan                         1
united stares                 1
australian                    1
jamaica                       1
unites states                 1
thailand                      1
colombia                      1
ghana                         1
ss                            1
burma                         1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [24]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

salary_by_state = df_salary_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

TypeError: dtype 'str' does not support operation 'mean'

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [ ]:
# Fix it.

df_salary_usd['salary'] = pd.to_numeric(df_salary_usd['salary'], errors='coerce')

Let’s try that again.

In [ ]:
# Try it again. Yeah!

salary_by_state = df_salary_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

print(salary_by_state.round(2))

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_usd['timestamp'] = pd.to_datetime(df_salary_usd['timestamp'])

df_year_filtered = df_salary_usd[df_salary_usd['timestamp'].dt.year.isin([2021, 2022, 2023])]
df_year_filtered.head()

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)